# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20170329_0801'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Produtos', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Usuarios', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
